[project]
name = "property-based-test-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "coverage>=7.13.4",
    "hypothesis>=6.0.0",
    "icontract>=2.6.0",
    "pandas==3.0.0",
    "pytest>=9.0.2",
]
